### ISSUE TITLE
HARNESS_OPTIONS support

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/test-cgi-external#11]
Could you add support for the HARNESS_OPTIONS environment variable, so that if it includes 'c' failures are printed in red?

**Comment by nigelhorne** [comment]
See [http://perldoc.perl.org/Test/Harness.html#ENVIRONMENT-VARIABLES-THAT-AFFECT-TEST%3a%3aHARNESS](url)

**Comment by benkasminbullock** [comment]
What's the expected behaviour here? I tried setting HARNESS_OPTIONS to the
value "c" like this:

export HARNESS_OPTIONS=c

If I set it like this:

export HARNESS_OPTIONS=unknownoption

I get an error message:

Unknown HARNESS_OPTIONS item: unknownoption

So since this is an environment variable, it seems already to be passed
through to the underlying module without having to do anything special. I'm
not sure what my module is doing which prevents the expected behaviour from
happening.

**Comment by nigelhorne** [comment]
I would like the fail messages to appear in red, however no colour appears.  Am I missing something?

**Comment by benkasminbullock** [comment]
The test messages are sent like this:

https://metacpan.org/source/BKB/Test-CGI-External-0.23/lib/Test/CGI/External.pm#L236

Here $self->{tb} is the instance of Test::Builder:

https://metacpan.org/source/BKB/Test-CGI-External-0.23/lib/Test/CGI/External.pm#L20

I'm not sure why the messages are not coming out in the expected colours, but my module doesn't remove the HARNESS_OPTIONS environment variable.

**Comment by benkasminbullock** [comment]
Further to this, I tried setting the thing to fail its tests by altering the above line to always fail, then ran 

    prove -I lib t/*.t 

and took a screenshot:

![not-ok-red](https://user-images.githubusercontent.com/102005/31573669-7976da9a-b0fb-11e7-9db0-c612e77598e2.png)

I can't reproduce the problem since the failed tests are coming out red even without the HARNESS_OPTIONS option set.

**Comment by nigelhorne** [comment]
I don't see the screen color when using T:C:E, but I do with 'make test' on CPAN modules.  So I don't know how to proceed - in particular a red line on a 'Not ok' would help a lot.

**Comment by benkasminbullock** [comment]
I don't have enough information about what the problem is to actually tackle this issue.
