### ISSUE TITLE
enhancement for do_compression_test

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/test-cgi-external#12]
Could you add to test more options work than just gzip?

**Comment by benkasminbullock** [comment]
What compression options are you considering? I don't know of anything other than gzip. Looking at the headers sent by Google Chrome, it only accepts 

HTTP_ACCEPT_ENCODING | gzip, deflate

With Firefox, it accepts

HTTP_ACCEPT_ENCODING | gzip, deflate

With microsoft edge,

HTTP_ACCEPT_ENCODING | gzip, deflate

I could add deflate I suppose, but deflate encoding on the web is broken anyway.

**Comment by nigelhorne** [comment]
deflate is the best other choice, but also brocolli, I mean Brotli.

**Comment by benkasminbullock** [comment]
Why would you want a test for deflate? It is completely unused on the web.

You can always test for whatever compression using your own test on
$options{body} as described in the module documentation. There doesn't seem
any point adding this to the module when no browser accepts the compression.

**Comment by benkasminbullock** [comment]
Also, the point I don't understand here is that the test for gunzip would work with deflate output anyway. If you're using deflate you could just use the gzip compression since deflate is indistinguishable from gzip. If you look at my module Gzip::Faster it documents that the gunzip does the same thing as inflate.

https://metacpan.org/pod/Gzip::Faster#inflate

>  Although the code is slightly different, for all practical purposes this is identical to "gunzip", and it's included only for completeness. In other words, you can use inflate and gunzip interchangeably.

The problem with deflate and internet explorer is documented all over the web.

I do appreciate these bug reports but one thing I wonder with this one and the other one about the output bug is whether you're using this to mock a CGI environment or whether you're doing something else with the module which it wasn't really intended to do. I'm going to close this and the other bugs.
