### ISSUE TITLE
I'd like to know what output it sees..

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/test-cgi-external#13]
I have a test failing with

"not ok 234 - The CGI executable produced some output"

I'd really like to know what that output is so that I can debug.  How do I find out?  verbose is on.

**Comment by benkasminbullock** [comment]
It doesn't see any output, that is the error. If a CGI executable doesn't produce even headers, the server will report an error to the user. If necessary I can add an option to switch this test off. But why would a CGI program produce no output at all?

**Comment by nigelhorne** [comment]
Surely it *shouldn't* have produced output, but it did.

**Comment by benkasminbullock** [comment]
Why would a CGI executable not produce any output? That is never a correct
behaviour since the server doesn't know what happened without any headers
or body of message. This tests whether the output is produced or not.

https://github.com/benkasminbullock/test-cgi-external/blob/master/lib/Test/CGI/External.pm#L398

The test fails if the output is not produced.

> I'd really like to know what that output is so that I can debug. How do I
find out? verbose is on.

Output is not being produced which is why the test fails. It does not make
sense for a CGI executable to not produce output.

You can check what is output using

https://metacpan.org/pod/Test::CGI::External#output

$test->run (\%options);
my $output = $options{output};

or what headers, body, errors, etc. are produced using the documented
outputs here:

https://metacpan.org/pod/Test::CGI::External#Outputs

This is documented in the module, I'm not sure what else to say to
this bug report.
